# Generated by Django 4.2.5 on 2023-10-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='MovieID',
            field=models.CharField(default=' ', max_length=20, primary_key=True, serialize=False),
        ),
    ]
