# Generated by Django 4.2.5 on 2023-10-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SavedMovies', '0001_initial'),
        ('MovieReviews', '0001_initial'),
        ('UserProfile', '0002_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemovies',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReviewMade',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='userID',
        ),
        migrations.AddField(
            model_name='profile',
            name='favoriteID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SavedMovies.favoritemovies'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviewID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieReviews.review'),
        ),
        migrations.AddField(
            model_name='profile',
            name='watched',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SavedMovies.watched'),
        ),
        migrations.AddField(
            model_name='profile',
            name='watchlistID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SavedMovies.watchlist'),
        ),
        migrations.DeleteModel(
            name='FavoriteMovies',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
