# Generated by Django 4.2.5 on 2023-10-10 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_alter_movie_movieid'),
        ('SavedMovies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='movieId',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='Movie.movie'),
        ),
    ]
