# Generated by Django 4.2.5 on 2023-10-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movie', '0001_initial'),
        ('Authentication', '0002_remove_favorites_movie_remove_favorites_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('movieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.movie')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.user')),
            ],
        ),
    ]
